### ISSUE TITLE
Does selectivesearch support python3?

### ISSUE THREAD

**Issue by dylansun** [AlpacaDB/selectivesearch#6]
ATT

**Comment by sdadia** [comment]
No, the PYPI page of selective does NOT state python 3 support. So I don't think it is supported in python 3.

**Comment by ZZ-yamashita-mg** [comment]
plz support python3...(´・ω・`)

**Comment by elitezhe** [comment]
oh...That explains why I come with such error:

> File "D:\miniconda3\envs\tensor\lib\site-packages\selectivesearch\__init__.py", line 1, in <module>
    from selectivesearch import selective_search  # NOQA
ImportError: cannot import name 'selective_search'

**Comment by elitezhe** [comment]
I convert these two py file to py3(No guarantee correct). 

It works like this: seems correct ^_^
![qq 20170515170330](https://cloud.githubusercontent.com/assets/3590003/26050238/73e84754-3990-11e7-94c6-0625a7984bf0.png)



[keras_mooc_ai.zip](https://github.com/AlpacaDB/selectivesearch/files/1000565/keras_mooc_ai.zip)

**Comment by elitezhe** [comment]
maybe should replace  line 287 

> i, j = sorted(list(S.items()), cmp=lambda a, b: cmp(a[1], b[1]))[-1][0]

with
`i, j = sorted(list(S.items()), key = lambda a: a[1])[-1][0]`
